### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [belopash/squid-typeorm-store#5]
Hi, I'm curious about your changelog: https://github.com/belopash/squid-typeorm-store/blob/master/CHANGELOG.md

```
#### 0.1.1 (2023-10-23)
#### 0.0.3 (2023-09-28)
#### 0.0.2 (2023-09-01)
#### 0.0.1 (2023-08-29)
#### 0.3.1 (2023-08-21)
#### 0.2.1 (2023-08-03)
#### 0.1.2 (2023-07-24)
#### 0.1.1 (2023-07-05)
#### 0.0.5 (2023-07-04)
#### 0.0.4 (2023-06-25)
#### 0.0.3 (2023-06-18)
#### 0.0.2 (2023-06-16)
#### 0.0.1 (2023-06-14)
```

It has multiple 0.0.{1,2,3} on different dates.
And also two 0.1.1 on 2023-07-05 and 2023-10-23).
I guess the one to use is the latest 0.1.1?

**Comment by belopash** [comment]
Hey, looks like something is broken with bump action, I will take a look. The latest version is 0.2.0

**Comment by belopash** [comment]
Btw, this package was made for personal usege and not a part of subsquid-sdk

**Comment by Hugo-Trentesaux** [comment]
Thanks for the answer ^^
I'm using it because it was a dependency of giant squid.
I like the `getOrFail` method used here: https://github.com/subsquid-labs/giant-squid-explorer/blob/a3d9b4f08ecbd918f18c87fc715e742cbdf145c4/src/main.ts#L51

- (giant squid) https://github.com/subsquid-labs/giant-squid-explorer
- BTW, this link is broken https://docs.subsquid.io/giant-squid-api/

Using it in my own experimentation on `duniter-squid`: https://git.duniter.org/HugoTrentesaux/duniter-squid/-/tree/main/src?ref_type=heads (note the `giant-squid.ts` file)

**Comment by belopash** [comment]
The main idea of this package is to allow you to delay and batch as many queries as possible. Using this package, you don't need to implement your own batch saving logic, as it runs under the hood, as well as cyclic dependencies resolving.

Feel free to use it if you want, feedback is much appreciated. I just wanted to warn you that this package is not part of the SDK 🙂
